version: '3.8'
services:
  assessment-mysql:
    platform: linux/x86_64
    image: mysql:5.7.34
    # volumes:
    #     - ~/volumes/jhipster/assessment/mysql/:/var/lib/mysql/
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=yourStrong(!)Password
      - MYSQL_DATABASE=assessment
    ports:
      - 3307:3306
    command: mysqld --lower_case_table_names=1 --skip-ssl --character_set_server=utf8mb4 --explicit_defaults_for_timestamp
